<?php


namespace SwagBundleExample\Core\Content\Bundle\Aggregate;


use Shopware\Core\Framework\DataAbstractionLayer\EntityTranslationDefinition;
use Shopware\Core\Framework\DataAbstractionLayer\FieldCollection;

class BundleTranslationDefinition extends EntityTranslationDefinition
{

    public const ENTITY_NAME = 'swag_bundle_translation';

    protected function getParentDefinitionClass(): string
    {
        parent::getParentDefinitionClass(); // TODO: Change the autogenerated stub
    }

    public function getEntityName(): string
    {
        return self::ENTITY_NAME;
    }

    protected function defineFields(): FieldCollection
    {
        // TODO: Implement defineFields() method.
    }
}
